\set database_name `echo "$PGDATABASE"`

DROP DATABASE IF EXISTS :"database_name";
CREATE DATABASE :"database_name";

\c :database_name

CREATE EXTENSION IF NOT EXISTS pgtap;

\ir 'schema/database.pg'

\ir 'schema/functions/stream/category.pg'
\ir 'schema/functions/stream/identifier.pg'
\ir 'schema/functions/stream/version.pg'
\ir 'schema/functions/stream/write_message.pg'

\ir 'schema/tables/messages.pg'

\ir 'schema/indexes/message_id.pg'
\ir 'schema/indexes/messages_category_global_position.pg'
\ir 'schema/indexes/messages_stream_name_position_uniq.pg'

\d
