\set database_name `echo "$PGDATABASE"`

DROP DATABASE IF EXISTS :"database_name";
CREATE DATABASE :"database_name";

\c :database_name
\ir 'schema/database.pgsql'

\ir 'schema/functions/stream/category.pgsql'
\ir 'schema/functions/stream/version.pgsql'
\ir 'schema/functions/stream/write_message.pgsql'

\ir 'schema/tables/messages.pgsql'

\ir 'schema/indexes/message_id.pgsql'
\ir 'schema/indexes/messages_category_global_position.pgsql'
\ir 'schema/indexes/messages_stream_name_position_uniq.pgsql'

\d
